package main

import (
	"bytes"
	"context"
	"crypto/ed25519"
	"d7024e/src/kademlia"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRegistryCLI(t *testing.T) {
	dir := t.TempDir()
	cwd, e := os.Getwd()
	if e != nil {
		t.Fatal(e)
	}
	if e = os.Chdir(dir); e != nil {
		t.Fatal(e)
	}
	defer os.Chdir(cwd)
	var generated bytes.Buffer
	if e = generateRegistryKeys("example.test", &generated); e != nil {
		t.Fatal(e)
	}
	keyFile := filepath.Join(dir, "publisher.json")
	if e = os.WriteFile(keyFile, generated.Bytes(), 0600); e != nil {
		t.Fatal(e)
	}
	owners, keys, e := loadRegistryKeys(keyFile)
	if e != nil || len(owners) != 1 || len(keys) != 1 {
		t.Fatal(e)
	}
	var output, diagnostics bytes.Buffer
	if e = os.WriteFile("source", []byte("package binary"), 0600); e != nil {
		t.Fatal(e)
	}
	commands := "show dns example.test\nshow dns unknown.test\npublish example.test:demo:1 source\npublish example.test:demo:2 source\nshow example.test:demo\nshow ds\ninstall example.test:demo:latest\ninstall example.test:demo:1\npublish --force --prev=0 example.test:demo:3 source\nexit\n"
	if e = run(context.Background(), []string{"-listen", "127.0.0.1:0", "-registry-keys", keyFile}, strings.NewReader(commands), &output, &diagnostics); e != nil {
		t.Fatal(e, diagnostics.String())
	}
	for _, want := range []string{"Published example.test:demo:1", "Published example.test:demo:2", "latest-pointer", "version-record", "Installed example.test:demo:latest", "Installed example.test:demo:1", "No owner key", "fork or rollback rejected"} {
		if !strings.Contains(output.String(), want) {
			t.Fatalf("missing %q: %s", want, output.String())
		}
	}
	for _, version := range []string{"1", "latest"} {
		data, e := os.ReadFile("example.test_demo_" + version + ".pkg")
		if e != nil || string(data) != "package binary" {
			t.Fatal(string(data), e)
		}
	}
	output.Reset()
	if e = run(context.Background(), []string{"-registry-keygen", "other.test"}, strings.NewReader(""), &output, &diagnostics); e != nil {
		t.Fatal(e)
	}
	var config registryKeys
	if e = json.Unmarshal(output.Bytes(), &config); e != nil || config.Seeds["other.test"] == "" {
		t.Fatal(e)
	}
}
func TestRegistryCLIValidation(t *testing.T) {
	dir := t.TempDir()
	file := filepath.Join(dir, "keys.json")
	if _, _, e := loadRegistryKeys(""); e != nil {
		t.Fatal(e)
	}
	if _, _, e := loadRegistryKeys(filepath.Join(dir, "missing")); e == nil {
		t.Fatal("missing config")
	}
	for _, input := range []string{"{", `{"owners":{"BAD":"abc"}}`, `{"owners":{"example.test":"aa"}}`, `{"seeds":{"example.test":"aa"}}`, `{"seeds":{"example.test":"` + strings.Repeat("00", 32) + `"}}`} {
		if e := os.WriteFile(file, []byte(input), 0600); e != nil {
			t.Fatal(e)
		}
		if _, _, e := loadRegistryKeys(file); e == nil {
			t.Fatal(input)
		}
	}
	if e := generateRegistryKeys("BAD", &bytes.Buffer{}); e == nil {
		t.Fatal("bad domain")
	}
	node := cliNode(t)
	var output bytes.Buffer
	for _, line := range []string{
		"publish --bad example.test:demo:1 x",
		"publish --prev=no example.test:demo:1 x",
		"publish bad x",
		"publish example.test:demo:latest x",
		"publish example.test:demo:1 /does/not/exist",
		"install bad",
		"install example.test:missing:1",
		"show bad",
		"show example.test:missing",
	} {
		if _, e := executeCommand(context.Background(), node, 1024, line, &output); e == nil {
			t.Fatal(line)
		}
	}
	source := filepath.Join(dir, "source")
	os.WriteFile(source, []byte("large"), 0600)
	if _, e := executeCommand(context.Background(), node, 1, "publish example.test:demo:1 "+source, &output); e != kademlia.ErrValueTooLarge {
		t.Fatal(e)
	}
	if _, e := executeCommand(context.Background(), node, 1024, "publish example.test:demo:1 "+source, &output, map[string]ed25519.PrivateKey{}); e == nil {
		t.Fatal("missing private key")
	}
	if e := run(context.Background(), []string{"-registry-keys", file}, strings.NewReader(""), &output, &output); e == nil {
		t.Fatal("invalid startup config")
	}
}
